### PR TITLE
chore: apply snakefmt

### PR DESCRIPTION
**Pull request by corneliusroemer**

### CODE REVIEW

**Comment by victorlin** [comment]
I'm assuming you have local configuration since CI's `snakefmt` didn't detect anything prior to this PR. Can you push your [configuration](https://github.com/snakemake/snakefmt#configuration) in a `pyproject.toml` file?

**Comment by corneliusroemer** [comment]
Ah, great point! I actually was confused that I needed to specify the folder explicitly and opened an issue https://github.com/snakemake/snakefmt/issues/202

I don't know why this isn't recognized, is it nested too deep? I don't have a `pyproject.toml`, I had to manually run `snakefmt` on the file (I saw VS code complain, the plugin is great).

**Comment by corneliusroemer** [comment]
Ah, we're getting there:
```bash
$ snakefmt -vv .
...snip...
[DEBUG] Excluded: ingest/workflow/snakemake_rules/trigger_rebuild.smk matched the --exclude regular expression
...snip...
```

**Comment by corneliusroemer** [comment]
Ok this is why:
```
DEFAULT_EXCLUDES = (
    r"(\.snakemake|\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|\.svn|_build|"
    r"buck-out|build|dist|\.template)"
)
```

**Comment by victorlin** [comment]
Haha yeah, I realized at the same time and commented as https://github.com/snakemake/snakefmt/issues/202#issuecomment-1731930527.

**Comment by corneliusroemer** [comment]
This is a terrible exclude, it matches anything that contains `build`...

I suggest we start using this in our config: ` snakefmt -vv --exclude "" .`

**Pull request merged**
