### PR TITLE
feat(ingest): add outbreak column from Nextclade output

### PR DESCRIPTION
**Pull request by corneliusroemer**

### CODE REVIEW

**Comment by corneliusroemer** [comment]
Tested and it seems to work!

**Comment by AngieHinrichs** [comment]
How do you get nextclade to produce the `outbreak` column?  I have nextclade 2.4.0 and don't see it:
```
nextclade dataset get --name hMPXV --output-zip hMPXV.zip
time nextclade run \
    -D hMPXV.zip \
    -j 30 \
    --output-tsv nextclade.tsv \
    --output-fasta nextalign.fa.xz \
    --retry-reverse-complement true \
    genbank.fa.xz
```

**Comment by corneliusroemer** [comment]
Strange @AngieHinrichs - could you share the exact files? The dataset zip and the Genbank fa xz? I'll try to reproduce.

My guess is you're not using the newest dataset? Maybe some caching issue? That would be the only sensible explanation I can think of.

**Comment by AngieHinrichs** [comment]
My mistake, I was using a hMPXV.zip downloaded about 10 hours ago.  Re-downloading it did the trick, sorry about the false alarm.

**Comment by corneliusroemer** [comment]
So you didn't actually run the code you shared to reproduce 🤣  Classic problem - you think you know what you did when in fact there's a subtle difference :)

**Pull request merged**
