### PR TITLE
improve script to fix trees

### PR DESCRIPTION
**Pull request by rneher**
this makes the fix tree script iterative and retains the proper substructure of newly created clades through merging,

### CODE REVIEW

**Comment by rneher** [comment]
@corneliusroemer this looks like it is working. Please have a look and merge

**Comment by corneliusroemer** [comment]
Just running it on the suboptimal tree from yesterday - will then merge. It'll remain for testing on the big build - but we could enable fixing any time on the other builds.

**Comment by corneliusroemer** [comment]
Excellent logging - works very well on the build - yesterday it only did iteration one, now it goes deeper.

image

**Review by corneliusroemer — APPROVED** [review]
Tested and works well

**Pull request merged**
